# - platform: generic
#   still_image_url: !secret camera_kyle_url
#   name: Kyle
#   username: !secret camera_kyle_username
#   password: !secret camera_kyle_password
#

- platform: mjpeg
  mjpeg_url: !secret camera_kyle_url
  name: Kyle
  username: !secret camera_kyle_username
  password: !secret camera_kyle_password
  authentication: !secret camera_kyle_auth

- platform: mjpeg
  mjpeg_url: !secret camera_kaylee_url
  name: Kaylee
  username: !secret camera_kaylee_username
  password: !secret camera_kaylee_password
  authentication: !secret camera_kaylee_auth

- platform: mjpeg
  mjpeg_url: !secret camera_front_url
  name: Front
  username: !secret camera_front_username
  password: !secret camera_front_password
  authentication: !secret camera_front_auth
